// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rpxtzdaflrzbgolutovu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJweHR6ZGFmbHJ6YmdvbHV0b3Z1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMDYyMTEsImV4cCI6MjA2MzU4MjIxMX0.caVfsfuZ0AUxYRmqUaID1sPj88sYa-w1czKSFtceDxM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);